### PR TITLE
Bump tools to latest

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
@kargakis for some reason not seeing the new unit job trigger here.

**Comment by kargakis** [comment]
Hrm, prow plugin config seems to be missing trigger for this repo.

**Comment by smarterclayton** [comment]
@aveshagarwal it looks like there are data races in the test code - can you help me fix those so we can turn on the job?

**Comment by aveshagarwal** [comment]
On Thu, Jun 7, 2018 at 9:34 PM Clayton Coleman <notifications@github.com>
wrote:

> @aveshagarwal <https://github.com/aveshagarwal> it looks like there are
> data races in the test code - can you help me fix those so we can turn on
> the job?
>

Sure.

**Comment by smarterclayton** [comment]
Any progress on getting these races fixed?

**Comment by aveshagarwal** [comment]
I have some fixes locally, but I am not near computer now as I am on
vacation this week. I will submit them as soon as I get a chance.

**Comment by aveshagarwal** [comment]
I am testing fixes locally and will send a PR to upstream/here soon.

**Comment by aveshagarwal** [comment]
I have opened a WIP PR upstream: https://github.com/kubernetes-incubator/cluster-capacity/pull/100 still doing some testing before going forward.

**Comment by aveshagarwal** [comment]
@smarterclayton so tests are passing now. I think we can go ahead with this PR.

**Comment by smarterclayton** [comment]
Great!

**Comment by aveshagarwal** [comment]
I am merging this now. I thought that it would get merged automatically after lgtm but does not seem to happen.

**Pull request merged**
