### PR TITLE
Bug 1808217: bump(golang.org/x/crypto)

### PR DESCRIPTION
**Pull request by damemi**

### CODE REVIEW

**Comment by ingvagabund** [comment]
From https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-capacity/33/pull-ci-openshift-cluster-capacity-release-4.3-unit/1:
```
hack/build-go.sh  
++ Building go targets for linux/amd64: cmd/hypercc
# github.com/kubernetes-incubator/cluster-capacity/cmd/cluster-capacity/app/options
cmd/cluster-capacity/app/options/options.go:92:16: soptions.ReallyApplyDefaults undefined (type *app.Options has no field or method ReallyApplyDefaults)
cmd/cluster-capacity/app/options/options.go:104:22: soptions.GetConfig undefined (type *app.Options has no field or method GetConfig)
```

**Comment by ingvagabund** [comment]
FYI there's nothing in the cluster-capacity code directly importing `golang.org/x/crypto/ssh`. It's imported by unit tests of vendored dependencies. Unfortunately, glide [1] does not allow to ignore/skip unit tests.

[1] https://glide.readthedocs.io/en/latest/glide.yaml/

**Comment by ingvagabund** [comment]
@damemi If you dare, it might be easier to migrate to godep. Though, I don't see the CVE as an issue here since the affected code is never executed in production.

**Comment by damemi** [comment]
@ingvagabund looking at other components' BZs it seems sufficient to close as irrelevant if we aren't actively using any of the functionality.

**Pull request closed without merging**
