### PR TITLE
Create RPM and image setup for cluster-capacity that matches origin

### PR DESCRIPTION
**Pull request by smarterclayton**
Tested:

    make

and

    hack/env make build-images

both of which were successful.

### CODE REVIEW

**Comment by smarterclayton** [comment]
@aveshagarwal you may want to play around with this to see what parts of your workflow I broke, but this is close to what image-registry has and matches what our jobs expect.

**Comment by aveshagarwal** [comment]
@smarterclayton thanks, will take a look soon.

**Comment by aveshagarwal** [comment]
@smarterclayton I reviewed changes in this PR, I am fine with changes in hack/, tool/, images/ and open-specifc spec file as they are specific to openshift and do not exist in upstream.

I have been trying to follow that in openshift fork, upstream stuff remains exactly same (to keep rebase cost low) and on top of it, we have openshift specific build tooling/other stuff.  

So I am wondering with changes in Makefile (also .gitignore  though not a big deal here). How can we have changes in these files to have compatible with upstream?  I'd prefer to have compatible changes in these files to go in upstream first and then we bring those changes via PR here. 

Plese let me know your thoughts.

**Comment by smarterclayton** [comment]
I would recommend renaming the upstream makefile in a carry patch and then
including it as necessary.  There may be future flexibility to rename the
makefile on our side, so that is something we can discuss.

I’m not sure upstream and our use case build requirements overlap.  I’m
always in favor of making the upstream more usable, but it’s not what I
would argue is a top priority.

On Apr 9, 2018, at 12:05 PM, Avesh Agarwal <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> I reviewed changes in
this PR, I am fine with changes in hack/, tool/, images/ and open-specifc
spec file as they are specific to openshift and do not exist in upstream.

I have been trying to follow that in openshift fork, upstream stuff remains
exactly same (to keep rebase cost low) and on top of it, we have openshift
specific build tooling/other stuff.

So I am wondering with changes in Makefile (also .gitignore though not a
big deal here). How can we have changes in these files to have compatible
with upstream? I'd prefer to have compatible changes in these files to go
in upstream first and then we bring those changes via PR here.

Plese let me know your thoughts.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/cluster-capacity/pull/11#issuecomment-379804855>,
or mute the thread

**Comment by aveshagarwal** [comment]
> I would recommend renaming the upstream makefile in a carry patch and then
including it as necessary.  There may be future flexibility to rename the
makefile on our side, so that is something we can discuss.

Instead of renaming upstream upstream file, I was thinking to have a Makefile.openshift (or whatever name) and using `-f Makefile.openshift` in the rpm spec file. As in openshift, we are driving everything via rpm spec file anyway. Is there any drawback of doing it?

**Comment by smarterclayton** [comment]
It's something you'll have to own in your automation, and it means someone who isn't familiar with your component in openshift will have to figure out the difference.  But it's fine for now.

**Comment by ingvagabund** [comment]
@aveshagarwal after this PR merges, we need to switch to PR-based rebasing. No more git push syncing.

**Comment by aveshagarwal** [comment]
I am merging this PR and builds are breaking it seems.

**Comment by ingvagabund** [comment]
```
$ rpm -q golang
golang-1.10-2.fc29.x86_64
```

```
hack/build-go.sh  
[FATAL] Detected Go version: go version go1.10 linux/amd64.
[FATAL] Builds require Go version go1.9 or greater.
[ERROR] PID 28319: hack/lib/build/binaries.sh:155: `( os::build::internal::build_binaries "${binaries[@]+"${binaries[@]}"}" )` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/lib/build/binaries.sh:155: `( os::build::internal::build_binaries "${binaries[@]+"${binaries[@]}"}" )`
[INFO] 		  2: hack/build-go.sh:20: os::build::build_binaries
[INFO]   Exiting with code 1.
[ERROR] hack/build-go.sh exited with code 1 after 00h 00m 00s
Makefile:41: recipe for target 'all' failed
make: *** [all] Error 1
```

This should be fixed in kube/openshift. Just need to find the patch.

**Comment by ingvagabund** [comment]
After applying:
* https://github.com/openshift/origin/pull/18445
* https://github.com/openshift/origin/pull/18807

and running ``OS_GIT_MAJOR=3 OS_GIT_MINOR=9 make build``, `make` runs without an error

**Pull request merged**
